spring:
  application.name: PipelineSafetyForecast
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor_data
    username: monitor
    password: temp_password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 1000
        keep-alive: 60s
      thread-name-prefix: async-


logging.level.org.springframework:
  security: DEBUG
  web: DEBUG
  boot.autoconfigure: DEBUG
  scheduling.concurrent.ThreadPoolTaskExecutor: DEBUG
